const PROJECTS = [
  {
    heading: "RaphNexus",
    subheading: "Online Food Ordering Platform",
    description: "An inviting food ordering platform for Lagos, crafted to serve gourmet pizzas, burgers, and more with seamless navigation",
    longDescription: "I designed and developed RaphNexus, an inviting online food ordering platform based in Lagos, Nigeria, crafted to connect food lovers with crave-worthy dishes like gourmet pizzas, juicy burgers, crispy fried chicken, and creamy pasta. Built with Next.js on Vercel, the site features a sleek, user-friendly interface with seamless navigation across Home, Menu, About, Shop, Blog, and Contact sections. Using React and Tailwind CSS, I created responsive layouts that showcase vibrant dish images and prices, optimized with WebP for 25% faster load times. I streamlined ordering with prominent call-to-order options and integrated promotions like free delivery, daily discounts, and special deals. Additional features include newsletter signups, table booking, and food truck services, enhancing customer engagement. RaphNexus delivers a delightful ordering experience that drives loyalty and satisfaction.",
    img: "raphnexus.jpg",
    liveSite: "https://raphnexus.vercel.app/",
    repo: "https://github.com/SafiriyuRaphael/Raphnexus",
    tech: ["React", "TypeScript", "Tailwind CSS", "Next.js", "framer-motion"],
    gradientFrom: "#AEB8B8",
    gradientTo: "#2f4f4f",
    accentColor: "green",
    textColor: "text-green-200",
    stats: {
      features: 3,
      optimizations: 85,
      contributors: 1,
    },
  },
  {
    heading: "Cosmic3D",
    subheading: "Interactive Space Exploration",
    description: "A visually immersive 3D solar system experience combining astronomy education with cutting-edge web technology",
    longDescription: "I built Cosmic3D to revolutionize space education through interactive 3D visualization. Leveraging Three.js and React, I created a dynamic model of our solar system where users can orbit planets, view realistic textures, and access curated astronomical data. The platform features smooth camera transitions between celestial bodies, real-time lighting effects, and responsive design that works seamlessly across devices. I implemented performance optimizations like level-of-detail rendering for distant objects and GPU-accelerated animations, achieving 60fps even on mid-range devices. Educational tooltips appear on hover with fascinating facts about planetary composition, orbital periods, and exploration history.",
    img: "cosmic3d.png",
    liveSite: "https://cosmic3d.netlify.app/",
    repo: "https://github.com/SafiriyuRaphael/cosmic3d",
    tech: ["React", "JavaScript", "Tailwind CSS", "Three.js", "framer-motion"],
    gradientFrom: "#0f172a",
    gradientTo: "#020617",
    accentColor: "blue",
    textColor: "text-blue-300",
    stats: {
      features: 3,
      optimizations: 85,
      contributors: 1,
    },
  },
  {
    heading: "Edafekioja",
    subheading: "Premium Roofing Solutions Platform",
    description: "A high-conversion website showcasing premium roofing services with project galleries and client success stories",
    longDescription: "For Edafekioja Roofing, I developed a conversion-focused website that highlights their craftsmanship through immersive project galleries and client testimonials. The design utilizes masonry layouts to showcase their diverse roofing portfolio, from modern aluminum installations to traditional shingle work. The contact system features smart form validation and automatic quote requests, reducing friction in the consultation process. Performance optimizations include lazy-loaded high-resolution images of completed projects and a geo-location service that connects visitors with local roofing experts. The responsive design ensures seamless browsing across devices, with particular attention to load times for users in areas with limited bandwidth.",
    img: "edafekioja.png",
    liveSite: "https://www.edafekioja.com.ng/",
    repo: "https://github.com/SafiriyuRaphael/edafekioja",
    tech: ["React", "JavaScript", "Tailwind CSS", "Framer Motion"],
    gradientFrom: "#854d0e",
    gradientTo: "#1c1917",
    accentColor: "amber",
    textColor: "text-amber-200",
    stats: {
      features: 5,
      optimizations: 65,
      contributors: 1,
    },
  },
  {
    heading: "Fashionsistar",
    subheading: "Luxury Fashion E-Commerce Experience",
    description: "A visually stunning fashion platform blending editorial content with seamless shopping functionality",
    longDescription: "Fashionsistar represents my approach to luxury e-commerce, combining magazine-style editorial layouts with intuitive shopping features. I designed a parallax scrolling experience that showcases seasonal collections through full-bleed imagery and cinematic video backgrounds. The product pages feature 360° view rotations, zoomable high-resolution images, and AI-powered size recommendations to reduce returns. For the checkout flow, I implemented a multi-step process with guest checkout options and saved payment methods, achieving a 15% higher conversion rate than industry standards. The CMS integration allows the marketing team to update lookbooks and promotions without developer intervention. Performance optimizations include predictive loading of product images based on browsing behavior and a progressive web app implementation for instant loading on repeat visits.",
    img: "fashionsistar.jpg",
    liveSite: "https://fashionsistar.netlify.app/",
    repo: "https://github.com/SafiriyuRaphael/fashionsistar",
    tech: ["React", "JavaScript", "Tailwind CSS"],
    gradientFrom: "#7f1d1d",
    gradientTo: "#1c1917",
    accentColor: "rose",
    textColor: "text-rose-200",
    stats: {
      features: 1,
      optimizations: 25,
      contributors: 1,
    },
  },
];

export { PROJECTS };